# Apple Music 下载器配置文件

# ========== 账号配置 ==========
accounts:
  - name: "CN"                                          # 账号名称，方便识别
    storefront: "cn"                                    # 账号所属区域（必须小写，如 cn, us, jp, hk）
    media-user-token: "${APPLE_MUSIC_MEDIA_USER_TOKEN_CN}"
    authorization-token: "${APPLE_MUSIC_AUTH_TOKEN_CN}"  # 授权令牌（可选，留空时程序自动获取）
    decrypt-m3u8-port: "127.0.0.1:10020"              # 解密服务端口
    get-m3u8-port: "127.0.0.1:10021"                  # M3U8获取服务端口

# ========== 路径配置 ==========
alac-save-folder: "/media/Music/AppleMusic/Alac"        # ALAC 无损音频保存路径
atmos-save-folder: "/media/Music/AppleMusic/Atmos"      # Dolby Atmos 音频保存路径
mv-save-folder: "/media/Music/AppleMusic/MusicVideos"   # MV 视频保存路径

# ========== 缓存配置 ==========
enable-cache: true                                      # 是否启用缓存机制（适用于网络文件系统）
cache-folder: "./Cache"                                 # 缓存文件夹路径（支持相对或绝对路径）

# ========== 下载性能配置 ==========
# M3U8 切片
chunk_downloadthreads: 30                               # M3U8 切片并行下载线程数
mv_chunk_downloadthreads: 30                            # MV 视频切片并行下载线程数

# 网络缓冲
NetworkReadBufferKB: 4096                               # 网络读取缓冲区大小（KB）
BufferSizeKB: 4                                         # I/O 缓冲区大小（KB），过大会导致内存占用过高

# 音频下载线程
aac_downloadthreads: 5                                  # AAC 格式下载线程数
lossless_downloadthreads: 5                             # 无损格式下载线程数
hires_downloadthreads: 5                                # Hi-Res 高解析度下载线程数

# MV 下载
mv_downloadthreads: 3                                   # MV 视频文件并行下载线程数

# 批量下载
batch-size: 20                                          # 每批处理的曲目数量（0 表示不分批）
skip-existing-validation: true                         # 自动跳过已存在文件的校验（true: 自动跳过, false: 询问用户）

# 工作-休息循环（仅批量模式生效）
work-rest-enabled: true                                # 是否启用工作-休息循环
work-duration-minutes: 30                                # 工作时长（分钟），建议 5-30 分钟
rest-duration-minutes: 2                                # 休息时长（分钟），建议 1-5 分钟


# ========== FFmpeg 配置 ==========
ffmpeg-fix: false                                        # 是否在下载完成后检测并修复编码问题
ffmpeg-check-args: "-map 0:a:0 -f wav -hide_banner -loglevel error -"      # FFmpeg 检测参数
ffmpeg-encode-args: "-c:v copy -c:a alac -avoid_negative_ts make_zero -f mp4 -y"  # FFmpeg 重编码参数

# ========== 语言配置 ==========
language: ""                                            # 语言代码（如 "zh-CN", "en-US"），留空则自动检测

# ========== 歌词配置 ==========
default-lyric-storefront: "cn"                          # 默认歌词区域
lrc-type: "lyrics"                                      # 歌词类型（lyrics: 普通歌词, syllable-lyrics: 逐字歌词）
lrc-format: "lrc"                                       # 歌词格式（lrc 或 ttml）
embed-lrc: true                                         # 是否将歌词嵌入音频文件
save-lrc-file: false                                    # 是否将歌词另存为 .lrc 文件

# ========== 封面配置 ==========
embed-cover: true                                       # 是否嵌入封面到音频文件
cover-size: "5000x5000"                                 # 封面尺寸
cover-format: "jpg"                                     # 封面格式（jpg, png, original）
save-artist-cover: true                                 # 是否保存歌手头像
save-animated-artwork: true                             # 是否保存动画插图（需要 ffmpeg）
emby-animated-artwork: true                             # 是否生成 Emby 动画插图（需要 ffmpeg）

# ========== 音频格式配置 ==========
get-m3u8-from-device: true                              # 是否从设备获取 M3U8
get-m3u8-mode: "hires"                                  # M3U8 获取模式（all: 获取所有, hires: 仅探测 Hi-Res）
aac-type: "aac-lc"                                      # AAC 类型（aac-lc, aac, aac-binaural, aac-downmix）
alac-max: 192000                                        # ALAC 最大采样率（192000, 96000, 48000, 44100）
atmos-max: 2768                                         # Atmos 最大码率（2768, 2448）

# ========== MV 配置 ==========
download-videos: true                                   # 是否下载 MV 视频
mv-audio-type: "atmos"                                  # MV 音轨偏好（atmos, ac3, aac）
mv-max: 2160                                            # MV 视频分辨率偏好（如 2160p, 1080p, 720p）

# ========== 路径限制 ==========
max-path-length: 255                                    # 绝对路径字符限制（Windows: 255, Linux/macOS: 4096）
limit-max: 200                                          # 歌手、专辑、曲目名的最大字符数

# ========== 文件命名格式 ==========
album-folder-format: "{AlbumName} {Tag}"                # 专辑文件夹命名格式
playlist-folder-format: "{PlaylistName}"                # 播放列表文件夹命名格式
song-file-format: "{SongNumer}. {SongName}"             # 歌曲文件命名格式
artist-folder-format: "{UrlArtistName}"                 # 艺术家文件夹命名格式（留空则不创建）

# ========== 音质标签配置 (v2.5.0+) ==========
# 控制专辑文件夹命名和曲目元数据中的音质标签
add-quality-tag-to-folder: true                         # 是否在专辑文件夹名称末尾添加音质标签（如 "Album Alac"）
add-quality-tag-to-metadata: true                       # 是否在曲目元数据的 ALBUM 和 ALBUMSORT 字段中添加音质标签

# 音质标签说明：
# - 启用两项配置：文件夹和元数据完全匹配，音乐管理软件能正确识别不同音质版本
# - 仅启用文件夹标签：文件按音质分类存储，但元数据中不体现音质
# - 仅启用元数据标签：文件夹名称简洁，音质信息仅在元数据中体现
# - 两项都禁用：文件夹和元数据都不包含音质标签（不推荐，可能导致版本混淆）
# 
# 建议配置：
# - 使用 Plex/Emby/Jellyfin：建议都启用（true）
# - 仅个人收藏：根据个人喜好配置

# ========== 特殊标签 ==========
explicit-choice: "[E]"                                  # 显式内容标识
clean-choice: "[C]"                                     # 净化版本标识
apple-master-choice: "[M]"                              # Apple Digital Master 标识

# ========== 播放列表元数据 ==========
use-songinfo-for-playlist: false                        # 是否为播放列表使用歌曲信息
dl-albumcover-for-playlist: false                       # 是否为播放列表下载专辑封面

# ========== 日志配置 ==========
logging:
  level: info                                           # 日志等级: debug/info/warn/error
  output: stdout                                        # 输出目标: stdout/stderr/文件路径
  show_timestamp: false                                 # UI模式下关闭时间戳
