package core

import (
	"main/utils/structs"
	"testing"
)

// 辅助函数：创建测试用的专辑元数据
func createTestMeta(id, name, artist string, isSingle bool, trackCount int) *structs.AutoGenerated {
	meta := &structs.AutoGenerated{}
	meta.Data = make([]struct {
		ID         string `json:"id"`
		Type       string `json:"type"`
		Href       string `json:"href"`
		Attributes struct {
			Artwork struct {
				Width      int    `json:"width"`
				Height     int    `json:"height"`
				URL        string `json:"url"`
				BgColor    string `json:"bgColor"`
				TextColor1 string `json:"textColor1"`
				TextColor2 string `json:"textColor2"`
				TextColor3 string `json:"textColor3"`
				TextColor4 string `json:"textColor4"`
			} `json:"artwork"`
			ArtistName           string   `json:"artistName"`
			IsSingle             bool     `json:"isSingle"`
			URL                  string   `json:"url"`
			IsComplete           bool     `json:"isComplete"`
			GenreNames           []string `json:"genreNames"`
			TrackCount           int      `json:"trackCount"`
			IsMasteredForItunes  bool     `json:"isMasteredForItunes"`
			IsAppleDigitalMaster bool     `json:"isAppleDigitalMaster"`
			ContentRating        string   `json:"contentRating"`
			ReleaseDate          string   `json:"releaseDate"`
			Name                 string   `json:"name"`
			RecordLabel          string   `json:"recordLabel"`
			Upc                  string   `json:"upc"`
			AudioTraits          []string `json:"audioTraits"`
			Copyright            string   `json:"copyright"`
			PlayParams           struct {
				ID   string `json:"id"`
				Kind string `json:"kind"`
			} `json:"playParams"`
			IsCompilation  bool `json:"isCompilation"`
			EditorialVideo struct {
				MotionTall struct {
					Video string `json:"video"`
				} `json:"motionTallVideo3x4"`
				MotionSquare struct {
					Video string `json:"video"`
				} `json:"motionSquareVideo1x1"`
				MotionDetailTall struct {
					Video string `json:"video"`
				} `json:"motionDetailTall"`
				MotionDetailSquare struct {
					Video string `json:"video"`
				} `json:"motionDetailSquare"`
			} `json:"editorialVideo"`
			EditorialNotes *structs.EditorialNotes `json:"editorialNotes"`
		} `json:"attributes"`
		Relationships struct {
			RecordLabels struct {
				Href string        `json:"href"`
				Data []interface{} `json:"data"`
			} `json:"record-labels"`
			Artists struct {
				Href string `json:"href"`
				Data []struct {
					ID         string `json:"id"`
					Type       string `json:"type"`
					Href       string `json:"href"`
					Attributes struct {
						Name    string `json:"name"`
						Artwork struct {
							Url string `json:"url"`
						} `json:"artwork"`
					} `json:"attributes"`
				} `json:"data"`
			} `json:"artists"`
			Tracks struct {
				Href string              `json:"href"`
				Next string              `json:"next"`
				Data []structs.TrackData `json:"data"`
			} `json:"tracks"`
		} `json:"relationships"`
	}, 1)

	meta.Data[0].ID = id
	meta.Data[0].Attributes.Name = name
	meta.Data[0].Attributes.ArtistName = artist
	meta.Data[0].Attributes.IsSingle = isSingle
	meta.Data[0].Attributes.TrackCount = trackCount

	return meta
}

// TestIsSingleAlbum 测试单曲专辑识别
func TestIsSingleAlbum(t *testing.T) {
	// 备份原始配置
	origConfig := Config
	defer func() { Config = origConfig }()

	// 启用虚拟 Singles 功能
	Config.EnableVirtualSingles = true

	tests := []struct {
		name     string
		meta     *structs.AutoGenerated
		expected bool
	}{
		{
			name:     "IsSingle 字段为 true",
			meta:     createTestMeta("album1", "Test Album", "Test Artist", true, 1),
			expected: true,
		},
		{
			name:     "专辑名称包含 '- Single'",
			meta:     createTestMeta("album2", "Test Song - Single", "Test Artist", false, 1),
			expected: true,
		},
		{
			name:     "专辑名称包含 ' Single'",
			meta:     createTestMeta("album3", "Test Song Single", "Test Artist", false, 1),
			expected: true,
		},
		{
			name:     "曲目数量为 1（单曲）",
			meta:     createTestMeta("album4", "Test Album", "Test Artist", false, 1),
			expected: true,
		},
		{
			name:     "曲目数量为 3（合作单曲）",
			meta:     createTestMeta("album5", "Collaboration EP", "Artist A & Artist B", false, 3),
			expected: true,
		},
		{
			name:     "正常专辑（10首曲目）",
			meta:     createTestMeta("album6", "Regular Album", "Test Artist", false, 10),
			expected: false,
		},
		{
			name:     "播放列表（应该跳过）",
			meta:     createTestMeta("pl.u-test123", "Playlist", "Apple Music", true, 1),
			expected: false,
		},
		{
			name:     "虚拟 Singles 功能未启用",
			meta:     createTestMeta("album7", "Test Song - Single", "Test Artist", true, 1),
			expected: false, // 会在测试中临时禁用
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// 特殊处理：测试虚拟 Singles 功能禁用的情况
			if tt.name == "虚拟 Singles 功能未启用" {
				Config.EnableVirtualSingles = false
				defer func() { Config.EnableVirtualSingles = true }()
			}

			result := IsSingleAlbum(tt.meta)
			if result != tt.expected {
				t.Errorf("%s: IsSingleAlbum() = %v, 期望 %v", tt.name, result, tt.expected)
			}
		})
	}
}

// TestGetPrimaryArtist 测试主艺术家提取
func TestGetPrimaryArtist(t *testing.T) {
	tests := []struct {
		name       string
		artistName string
		expected   string
	}{
		{
			name:       "单个艺术家",
			artistName: "Taylor Swift",
			expected:   "Taylor Swift",
		},
		{
			name:       "使用 & 分隔的合作",
			artistName: "Artist A & Artist B",
			expected:   "Artist A",
		},
		{
			name:       "使用 feat. 的合作",
			artistName: "Main Artist feat. Featured Artist",
			expected:   "Main Artist",
		},
		{
			name:       "使用 & 和 feat. 的复杂合作",
			artistName: "Primary Artist feat. Second Artist & Third Artist",
			expected:   "Primary Artist feat. Second Artist",
		},
		{
			name:       "使用逗号分隔的合作（中文）",
			artistName: "好妹妹, 秦昊Jeff, 张小厚",
			expected:   "好妹妹",
		},
		{
			name:       "使用顿号分隔的合作（中文）",
			artistName: "陈婧霏、王加一、韦唯",
			expected:   "陈婧霏",
		},
		{
			name:       "使用斜杠分隔的合作",
			artistName: "Artist A / Artist B",
			expected:   "Artist A",
		},
		{
			name:       "空字符串",
			artistName: "",
			expected:   "",
		},
		{
			name:       "带前后空格的艺术家名",
			artistName: "  Artist Name  ",
			expected:   "  Artist Name  ",
		},
		{
			name:       "实际案例：Alec Benjamin & 陈婧霏",
			artistName: "Alec Benjamin & 陈婧霏",
			expected:   "Alec Benjamin",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := GetPrimaryArtist(tt.artistName)
			if result != tt.expected {
				t.Errorf("%s: GetPrimaryArtist(%q) = %q, 期望 %q",
					tt.name, tt.artistName, result, tt.expected)
			}
		})
	}
}

// TestGetVirtualSinglesTrackNumber 测试虚拟 Singles 曲目编号分配
func TestGetVirtualSinglesTrackNumber(t *testing.T) {
	// 使用临时艺术家名以不影响其他测试
	artist := "Test Artist " + t.Name()

	// 测试连续分配
	num1 := GetVirtualSinglesTrackNumber(artist)
	num2 := GetVirtualSinglesTrackNumber(artist)
	num3 := GetVirtualSinglesTrackNumber(artist)

	if num1 != 1 {
		t.Errorf("第一个编号应为 1，实际为 %d", num1)
	}
	if num2 != 2 {
		t.Errorf("第二个编号应为 2，实际为 %d", num2)
	}
	if num3 != 3 {
		t.Errorf("第三个编号应为 3，实际为 %d", num3)
	}

	// 测试不同艺术家独立计数
	artist2 := "Another Artist " + t.Name()
	num4 := GetVirtualSinglesTrackNumber(artist2)

	if num4 != 1 {
		t.Errorf("另一个艺术家的第一个编号应为 1，实际为 %d", num4)
	}
}
